# Generated by Django 5.1.4 on 2025-02-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(default='Full-time', max_length=50)),
                ('skills_preferred', models.TextField(blank=True, null=True)),
                ('education_preferred', models.TextField(blank=True, null=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter')),
            ],
            options={
                'unique_together': {('title', 'company', 'experience', 'location')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resume/')),
                ('email', models.EmailField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('current_company', models.TextField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('current_education', models.TextField(blank=True, null=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker')),
                ('recruiter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter')),
                ('jobinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobinfo')),
            ],
        ),
    ]
